config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update]
  resources :photos, only: [:new, :create, :index, :show] do
    put "like", to: "photos#like"
    put "dislike", to: "photos#dislike"
  end
  resources :sessions, only: [:new, :create]
  resource :comments, only: [:create]

  namespace :api, constraints: { format: 'json' } do
    resources :photos, only: [:show, :index]
    resources :comments, only: [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  acts_as_votable

  belongs_to :user
  has_many :comments
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_many :comments
  has_many :photos
  has_secure_password
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
  end
end

app/controllers/api/comments_controller.rb
module Api
  class CommentsController < ApplicationController
    def index
      @comments = Comment.all
    end

    def show
      @comment = Comment.find(params[:id])
    end
  end
end

app/controllers/api/photos_controller.rb
module Api
  class PhotosController < ApplicationController
    def index
      @photos = Photo.all
    end

    def show
      @photo = Photo.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def authorize
      redirect_to "/", alert: "Not authorized" if current_user.nil?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize

  def create
    comment = Comment.new(comment_params)
    comment.user_id = session[:user_id]

    if comment.save
      redirect_to photo_path(comment.photo_id)
    else
      redirect_to "/"
    end
  end

  private
    
    def comment_params
      params.require(:comment).permit(:body, :photo_id)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authorize

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end
  
  def create
    photo = Photo.new(photo_params)
    photo.user_id = session[:user_id]

    if photo.save
      redirect_to :photos
    else
      redirect_to "/"
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
    @comments = @photo.comments
  end

  def like
    photo = Photo.find(params[:photo_id])
    photo.upvote_by current_user
    redirect_to photo_path(photo.id)
  end

  def dislike
    photo = Photo.find(params[:photo_id])
    photo.downvote_by current_user
    redirect_to photo_path(photo.id)
  end

  private

    def photo_params
      params.require(:photo).permit(:image_name, :image, :title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to :photos, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    
    if user.save
      session[:user_id] = user.id
      redirect_to photos_path
    else
      redirect_to "/"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])

    if user.update(user_params)
      redirect_to edit_user_path(user.id)
    else
      redirect_to "/"
    end
  end

  private
    
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<h1>All Photos</h1>

<% @photos.each do |photo| %>
  <%= image_tag photo.image.url(:medium) %>
  <%= link_to "View", photo_path(photo.id) %>
  <hr>
<% end %>

app/views/photos/new.html.erb
<h1> Upload a Photo </h1>

<%= form_for @photo, html: { multipart: true } do |f| %>
  Photo title: <%= f.text_field :title %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/photos/show.html.erb
<h1> Your Photo </h1>
<h1> <%= @photo.title %> </h1>

<%= image_tag @photo.image.url(:medium) %>

<hr>

<%= link_to photo_like_path(@photo.id), method: :put do %>
  Like
<% end %>
|
<%= link_to photo_dislike_path(@photo.id), method: :put do %>
  Dislike
<% end %>

<p> Likes: <%= @photo.get_likes.size %> </p>
<p> Dislikes: <%= @photo.get_dislikes.size %> </p>

<hr>

<h1>Comments</h1>

<%= @comments.each do |comment| %>
  <p> From <%= comment.user.first_name %> </p>
  <p> <%= comment.body %> </p>
<% end %>

<hr>

<hr>

<%= form_for @comment, url: comments_path do |f| %>
  <%= f.hidden_field :photo_id, value: @photo.id %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1> Edit Your Profile </h1>

<hr />

<%= form_for @user do |f| %>
  First name: <%= f.text_field :first_name %><br />
  Last name : <%= f.text_field :last_name %><br />
  Email : <%= f.text_field :email %><br />
  Password : <%= f.text_field :password %><br />
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1> SIGN UP FOR INSTAGRAM </h1>

<hr />

<%= form_for @user do |f| %>
  First name: <%= f.text_field :first_name %><br />
  Last name : <%= f.text_field :last_name %><br />
  Email : <%= f.text_field :email %><br />
  Password : <%= f.text_field :password %><br />
  <%= f.submit %>
<% end %>